---
env:
  node: true
  jest/globals: true

parserOptions:
  project: 'tsconfig.json'

plugins:
  - jest

extends:
  - '@acmecryptocorp'
  - '@acmecryptocorp/eslint-config/typescript'
  - plugin:jest/recommended
  - plugin:jest/style

rules:
  filenames/match-exported: off
  import/prefer-default-export: off
  import/extensions:
    - error
    - ignorePackages
